### ISSUE TITLE
Will this plugin work on Volumio 3?

### ISSUE THREAD

**Issue by anLizard** [Saiyato/volumio-snapclient-plugin#3]
My Raspberry Pi Zero W recently died, so I am replacing it with a Pi Zero 2 W, but it is still in the mail.

The Pi Zero 2 W's Wifi currently does not work on Volumio 2, but it works on Volumio 3.
The devs also mentioned plugin's for Volumio 2 don't work with Volumio 3.

Does this plugin work for for Volumio 3, or if no, is there an update for Volumio 3 planned?

**Comment by anLizard** [comment]
Installed it on Volumio 3 RC1, Raspberry Pi Zero 2. Unfortunatly it doesn't seem to work.

After booting, the plugin show as inactive, even when it is turned on.
Turning it on and off makes it show up as active, but sound played on the server does not get played on the client.

**Comment by Saiyato** [comment]
Let me dive into this one as well, I'm going to need to build a different lab, so it will take a bit longer than the server-part :wink:
Only tested this on x86 (some time ago), so I will retest on the pi platform.

**Comment by Saiyato** [comment]
I see the unit has trouble writing the pid-file in /var/run/snapclient (because of insufficient rights). So the problem is found, now a graceful solution :wink:

```
Dec 02 19:40:17 volumiotest systemd[1]: Started Snapcast client.
Dec 02 19:40:17 volumiotest snapclient[8626]: daemonizing
Dec 02 19:40:17 volumiotest snapclient[8626]: Exception: Could not open PID lock file "/var/run/snapclient/pid"
Dec 02 19:40:17 volumiotest snapclient[8626]: Snapclient terminated.
```

**Comment by Saiyato** [comment]
I think it's our lucky day! I found this comment:
`
You shouldn't be passing the "-d" option to the client if you are running it through systemd. (This holds for any type of process, not only snapclient, unless you set the systemd type to "forking".)
The idea is that systemd can start up and track the snapclient process, including keeping track of the stdout and stderr.

If you pass on "-d" then it will look to systemd like the process started and immediately quit again because it will fork itself into another thread which systemd has no control over. Systemd will hence try to restart the process again (ending up in a loop).

The "-d" option is only useful if you start snapclient on the command line and you want it to fork itself into a separate process that will still continue if you close the terminal.
`
source: https://github.com/badaix/snapcast/issues/547#issuecomment-598204812

I will amend! A quick test is successful 😄

**Comment by Saiyato** [comment]
Can you retest with v1.0.3 please?

**Comment by anLizard** [comment]
> Can you retest with v1.0.3 please?

JUST turned off my PC... I'll make sure to test tomorrow and will report back!

**Comment by Saiyato** [comment]
Haha, no worries, take your time! I'm still waiting to upgrade my production Pi. So you're actually the first one to test :wink:

As for the Volumio 3 compatibility, this mostly has to do with the distro's upgrade (which is actually beneficial for most of my plugins), so I'm not afraid about compatibility in any way.

**Comment by anLizard** [comment]
It works!! Just one small caveat is still present:

Uninstalled old plugin, rebooted, installed new version, and enabled plugin, rebooted.
Snapclient plugin shows up as inactive after boot. Disabling and re-enabling fixes this, then it works.

![image](https://user-images.githubusercontent.com/48686356/144591408-a71a923b-7ed4-4b5e-a47c-eca3ea5913dd.png)

**Comment by Saiyato** [comment]
Can you retest with v1.0.4 please? I added a defer.resolve() to the onStart sequence.
Also, for some reason the previous installation of SnapServer caused the server to not start... reinstalling the plugin fixed this. (Very weird)

**Comment by anLizard** [comment]
Uninstalled old version and ran `./volumio_install_from_zip.sh Saiyato volumio-snapclient-plugin`, but it installed 1.0.3 again.

Also tried again but deleted `/home/volumio-snapclient-plugin` before hand, still only 1.0.3

**Comment by Saiyato** [comment]
Apologies! Was not yet pushed to GH, just pushed the new version. Sorry

**Comment by anLizard** [comment]
Fixed on new version!
Thank you SO SO much for porting the plugin to Volumio 3 and ironing out the bugs!
Snapcast was the only thing I was missing for my installation, and now my multiroom setup works perfectly again, you are a saint!

**Comment by Saiyato** [comment]
You're welcome, thanks for the patience, much appreciated
